### ISSUE TITLE
1.0 Release Checklist

### ISSUE THREAD

**Issue by SpicyPete** [Bitcoin-com/badger-mobile#58]
# 1.0 Release Checklist 

- [x] Update ToS legalese for Badger Mobile
- [x] Add a clear "contact us" link in app
- [x] Prepare Android Release
- [x] Prepare iOS Release
- [x] ToS hosted on badger.bitcoin.com
- [x] Privacy Policy hosted on badger.bitcoin.com
- [x] Beta Testing
- [x] Update badger.bitcoin.com with mobile store links
- [x] Merge release into Master and tag release.

## Android Release

[Reference](https://support.google.com/googleplay/android-developer/answer/113469?hl=en)  
[Play Store Checklist](https://developer.android.com/distribute/best-practices/launch/launch-checklist)

- [x] Get Developer play account
- [x] Get .apk signing keys
- [x] Generate a build with signing keys
- [x] Upload to play store process
- [x] Take app screenshots
- [x] Setup store listing
- [x] Minor store Beta / testing
- [x] Release

## iOS Release

[Reference](https://medium.com/@the_manifest/how-to-publish-your-app-on-apples-app-store-in-2018-f76f22a5c33a)  
[Store Guidelines](https://developer.apple.com/app-store/review/guidelines/)

- [x] Get iOS store account
- [x] Prepare screenshots / metadata
- [x] Submit for review
- [x] Start testflight
- [x] Release

**Comment by SpicyPete** [comment]
1.0 is completed.  Now for updates
